# Tensor object in PyTorch package
### Author : Mohamed Kadhem KARRAY 

- Website: https://mohamedkadhem.com
- Youtube: https://www.youtube.com/@mohamedkadhemkarray2504
- LinkedIn: https://www.linkedin.com/in/mohamed-kadhem-karray-b21895b

Date: 2023 september 19th

### Content
- The PyTorch package proposes a type of object, called Tensor, which is a multidimensional matrix.
- This notebook, based on  [1], presents the basic operations one may make with Tensors. 

References

[1] M. Lelarge et al., https://dataflowr.github.io/website

## Install packages

- The following code permits to install the package with "pip" command.
  - If the package is already installed on your machine, then you may pass this step.
  - Otherwise, exceute the following code (desactivate the proxy, if necessary).

In [1]:
# Installing package using "pip" command.
# Since we run a DOS command, we begin it with "!".
!pip install torch

## Import packages

In [2]:
import torch
import numpy as np

## A tensor is multidimensional matrix

In [4]:
x=torch.ones(2,4,3) # matrix of dimension 2×4×3
y=x.numpy() # convert from torch to numpy
z=torch.from_numpy(y) # convert from numpy to torch
print("y=",y)
print("z=",z)

y= [[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
z= tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])


## Types and precision

In [7]:
x=torch.randn(4)
a=torch.from_numpy(np.ones(4))
print("a=",a) # tensor([1., 1., 1., 1.], dtype=torch.float64)
b=a.float()
print("b=",b) # tensor([1., 1., 1., 1.])
print("Test (x+a)==(x+b):",(x+a)==(x+b)) # Result: tensor([False, False, False,  True])

a= tensor([1., 1., 1., 1.], dtype=torch.float64)
b= tensor([1., 1., 1., 1.])
Test (x+a)==(x+b): tensor([ True, False,  True, False])


## Broadcasting

 - When adding two tensors, their sizes are expanded to be of equal sizes (by replicating coefficients).
   - More details on https://pytorch.org/docs/stable/notes/broadcasting.html.


In [8]:
x=torch.tensor([[1.], [10.]]) # column vector 2×1
print(x)
y=torch.tensor([[0, 1]]) # row vector 1×2
print(y)
print((x+y)) # matrix 2×2

tensor([[ 1.],
        [10.]])
tensor([[0, 1]])
tensor([[ 1.,  2.],
        [10., 11.]])


## In-place modification

In [9]:
x=torch.tensor([1])
y=x.add(-1)
print("x=",x) # Result: tensor([1])
y=x.add_(-1) # The sign '_' modifies x in-place
print("x=",x) # Result: tensor([0])

x= tensor([1])
x= tensor([0])


## Shared memory

- The torch tensor and the associated numpy array share the same memory.

In [12]:
a=np.ones(2)
b=torch.from_numpy(a)
a[0]=0
print("b=",b) # Result: tensor([0., 1.]
b[1]=2
print("a=",a) # Result: [0. 2.]

b= tensor([0., 1.], dtype=torch.float64)
a= [0. 2.]


## torch.unsqueeze

- torch.unsqueeze(input, position): generates a new tensor as output by adding a new dimension of size one at the desired position.

In [15]:
x=torch.tensor([10, 2, 5, 37])
print("Shape of x:", x.shape)
x0=torch.unsqueeze(x,0) 
print("x0=torch.unsqueeze(x,0)=",x0)
print("Shape of x0:", x0.shape)
x1=torch.unsqueeze(x,1)
print("x1=torch.unsqueeze(x,1)=",x1)
print("Shape of x1:",x1.shape)

Shape of x: torch.Size([4])
x0=torch.unsqueeze(x,0)= tensor([[10,  2,  5, 37]])
Shape of x0: torch.Size([1, 4])
x1=torch.unsqueeze(x,1)= tensor([[10],
        [ 2],
        [ 5],
        [37]])
Shape of x1: torch.Size([4, 1])
